/*
Copyright 2018 Pearson Technology

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	vaultpolicy_v1 "github.com/pearsontechnology/bitesize-controllers/vault-controller/pkg/apis/vault.local/v1"
	versioned "github.com/pearsontechnology/bitesize-controllers/vault-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pearsontechnology/bitesize-controllers/vault-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/pearsontechnology/bitesize-controllers/vault-controller/pkg/client/listers/vaultpolicy/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// VaultPolicyInformer provides access to a shared informer and lister for
// VaultPolicies.
type VaultPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VaultPolicyLister
}

type vaultpolicyInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewVaultPolicyInformer constructs a new informer for VaultPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVaultPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.VaultPolicyV1().VaultPolicies().List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.VaultPolicyV1().VaultPolicies().Watch(options)
			},
		},
		&vaultpolicy_v1.VaultPolicy{},
		resyncPeriod,
		indexers,
	)
}

func defaultVaultPolicyInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewVaultPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *policyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vaultpolicy_v1.VaultPolicy{}, defaultVaultPolicyInformer)
}

func (f *policyInformer) Lister() v1.VaultPolicyLister {
	return v1.NewPolicyLister(f.Informer().GetIndexer())
}
